name: Build Pixel Experience GSI

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build GSI

    steps:
    - name: Checkout treble_pixel repository
      uses: actions/checkout@v2
      with:
        repository: 'kwokdelee/treble_build_pe'
        token: ${{ secrets.GITHUB_TOKEN }}
        path: 'treble_pixel'

    - name: Install repo command
      run: |
        mkdir -p ~/bin
        PATH=~/bin:$PATH
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+rx ~/bin/repo
        echo "PATH=~/bin:$PATH" >> $GITHUB_ENV

    - name: Initialize and sync repositories
      run: bash treble_build_pe/build.sh initRepos
      working-directory: ${{ github.workspace }}

    - name: Apply patches and setup environment
      run: bash treble_build_pe/aplypatches.sh applyPatches && bash treble_build_pe/build.sh setupEnv
      working-directory: ${{ github.workspace }}

    - name: Build variants
      run: bash treble_build_pe/build.sh buildVariant && bash treble_build_pe/build.sh buildVndkliteVariant
      working-directory: ${{ github.workspace }}
