name: Build GSI ROM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          bc bison build-essential curl flex g++-multilib gcc-multilib git \
          gnupg gperf libxml2 lib32z1-dev liblz4-tool libncurses5-dev \
          libsdl1.2-dev libwxgtk3.0-gtk3-dev imagemagick git lunzip \
          lzop schedtool squashfs-tools xsltproc zip zlib1g-dev \
          openjdk-8-jdk python perl xmlstarlet virtualenv xz-utils rr jq \
          libncurses5 pngcrush lib32ncurses5-dev git-lfs openjdk-11-jdk-headless

      - name: Set up Repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
          source ~/.bashrc

      - name: Initialize the ROM source
        run: |
          mkdir ~/rom && cd ~/rom
          repo init -u https://github.com/LineageOS/android.git -b lineage-19.1
          git clone https://github.com/phhusson/treble_manifest .repo/local_manifests -b android-12.0
          repo sync -c -j6 --force-sync --no-tags --no-clone-bundle

      - name: Build the GSI
        run: |
          source build/envsetup.sh
          lunch treble_arm64_avN-userdebug
          WITHOUT_CHECK_API=true make -j$(nproc) systemimage

      - name: Compress the system image
        run: |
          cd out/target/product/phh_*/
          xz -9 -T0 -v -z system.img
